#!/usr/bin/env bash
# This script checks and configures Nginx settings for port 80, stopping conflicting Apache services, and adjusts firewall settings if needed.

# remove the default Nginx configuration file
rm /etc/nginx/sites-enabled/default
# Configure Nginx to listen on port 80 for all active IPv4 IPs
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx restart
