#!/usr/bin/env bash
# This script configures Nginx for port 80, stops conflicting Apache, and adjusts firewall.

# Remove default Nginx config if it exists
if [[ -e /etc/nginx/sites-enabled/default ]]; then
    rm /etc/nginx/sites-enabled/default
fi

# Create symbolic link to enable Nginx on port 80 for all IPv4
if [[ ! -e /etc/nginx/sites-enabled/default ]]; then
    ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
fi

# Restart nginx only if it's not running
if ! systemctl is-active --quiet nginx; then
    systemctl restart nginx
fi
