#!/usr/bin/env bash
# This script configures Nginx for port 80, stops conflicting Apache, and adjusts firewall.

# Remove default Nginx config
rm /etc/nginx/sites-enabled/default

# Configure Nginx to listen on port 80 for all IPv4
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

# Restart nginx
systemctl restart nginx
