#!/usr/bin/env bash
#Configures an Nginx server to listen on port 80

#creates a symbolic link (-s option) between the Nginx configuration file
#and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
#restart nginx
serice nginx start
#terminate the first nginx process ID
Kill "$(pgrep 'nginx' | -1)"
